routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('data-bank', 'dataBankController');
Route::resource('jenis-cuti', 'jenisCutiController');
Route::get('tambah-data-cuti', function () {
    return view('pages.jenisCuti.form');
});
Route::resource('jenis-golongan', 'jenisGolonganController');
Route::resource('jabatan', 'dataJabatanController');
Route::resource('jenis-potongan', 'jenisPotonganController');
Route::resource('komponen-gaji', 'komponenGajiController');
Route::resource('karyawan-tetap', 'karyawanTetapController');
Route::resource('karyawan-kontrak', 'karyawanKontrakController');
Route::resource('kontrak-karyawan', 'dataKontrakController');

app/Http/Controllers/jenisPotonganController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\jenisPotongan;

class jenisPotonganController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = jenisPotongan::all();
        return view('pages.jenisPotongan.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.jenisPotongan.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nip' => 'required|min:4',
            'desc' => 'required|min:20',
            'nominal' => 'required|min:4',
            'flag' => 'required',
        ]);

         $data = new jenisPotongan();
       $data->nip = $request->nip;
       $data->desc = $request->desc;
       $data->nominal = $request->nominal;
       $data->tgl_ambil = $request->tglAmbil;
       $data->flag = $request->flag;
       $data->save();
       return redirect()->route('jenis-potongan.index')->with('alert-success','Berhasil Menambahkan Jenis Potongan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $ids = $request->idd;
        $datas = jenisPotongan::where('id',$ids)->first();
        $datas->nip = $request->nip;
        $datas->desc = $request->desc;
        $datas->nominal = $request->nominal;
        $datas->tgl_ambil = $request->tglAmbil;
        $datas->flag = $request->flag;
        $datas->save();
        return redirect()->route('jenis-potongan.index')->with('alert-success','Berhasil diUpdate Jenis Potongan!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $datas = jenisPotongan::where('id',$id)->first();
        $datas->flag = 0;
        $datas->save();
        return redirect()->route('jenis-potongan.index')->with('alert-success','Berhasil diHapus Jenis Potongan!');
    }
}

resources/views/pages/jenisPotongan/data.blade.php
<div class="container-fluid">
		<h2>Table Data Potongan</h2>
		<hr>
		<table class="table table-bordered">
			<thead class="table-primary">
				<tr>
					<th>Nip</th>
					<th>Deskripsi</th>
					<th>Nominal</th>
					<th>Tanggal Ambil</th>
					<th>Flag</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				@foreach($data as $datas)
				<tr>
					<th>{{ $datas->nip }}</th>
					<th>{{ $datas->desc }}</th>
					<th>{{ $datas->nominal }}</th>
					<th>{{ $datas->tgl_ambil }}</th>
					<th>{{ $datas->flag }}</th>
					<td>
						<form action="{{ route('jenis-potongan.destroy', $datas->id) }}" method="POST">
							{{ csrf_field() }}
							{{ method_field('DELETE') }}
							<a href="#"  data-toggle="modal" data-target="#exampleModal" data-nip="{{$datas->nip}}" data-desc="{{$datas->desc}}" data-nominal="{{$datas->nominal}}" data-tglambil="{{$datas->tgl_ambil}}" data-idd="{{$datas->id}}" class="btn btn-sm btn-primary">Edit</a>
							<button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
						</form>
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Data</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('jenis-potongan.update', 1) }}" method="POST" >
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <input type="hidden" readonly="readonly" class="form-control idd" name="idd" required="required">
                    <div class="form-group">
                        <label for="nip">Nip</label>
                        <input type="number" class="form-control nip" name="nip" required="required">
                    </div>
                    <div class="form-group">
                        <label for="desc">Deskripsi</label>
                        <textarea class="form-control desc" name="desc" required="required" style="resize: none;"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="nominal">Nominal</label>
                        <input type="number" class="form-control nominal" name="nominal" required="required">
                    </div>
                    <div class="form-group">
                        <label for="tglAmbil">Tanggal Ambil</label>
                        <input type="date" class="form-control tgll" name="tglAmbil" required="required">
                    </div>
                    <div class="form-group">
                        <label for="flag">Flag</label>
                        <select class="form-control" name="flag">
                            <option value="1">Active</option>
                            <option value="0">Non Active</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-md btn-primary">Submit</button>
                        <button type="reset" class="btn btn-md btn-danger">Cancel</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>

<script>
    $('#exampleModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget)
        var nip = button.data('nip')
        var desc = button.data('desc')
        var nominal = button.data('nominal')
        var tgl = button.data('tglambil')
        var id = button.data('idd')
        var modal = $(this)

        modal.find('.modal-body .nip').val(nip)
        modal.find('.modal-body .desc').val(desc)
        modal.find('.modal-body .nominal').val(nominal)
        modal.find('.modal-body .tgll').val(tgl)
        modal.find('.modal-body .idd').val(id)
    })
</script>

resources/views/pages/jenisPotongan/form.blade.php
<div class="container-fluid">
		<h2>Input Data Potongan</h2>
		<hr>
		@if ($errors->any())
	    <div class="alert alert-danger">
	        <ul>
	        @foreach ($errors->all() as $error)
	            <li>{{ $error }}</li>
	        @endforeach
	        </ul>
	    </div>
	    @endif
		<form action="{{ route('jenis-potongan.store') }}" method="POST" >
			{{ csrf_field() }}
			<div class="form-group">
				<label for="nip">Nip</label>
				<input type="number" class="form-control" name="nip" required="required">
			</div>
			<div class="form-group">
				<label for="desc">Deskripsi</label>
				<textarea class="form-control" name="desc" required="required" style="resize: none;"></textarea>
			</div>
			<div class="form-group">
				<label for="nominal">Nominal</label>
				<input type="number" class="form-control" name="nominal" required="required">
			</div>
			<div class="form-group">
				<label for="tglAmbil">Tanggal Ambil</label>
				<input type="date" class="form-control" name="tglAmbil" required="required">
			</div>
			<div class="form-group">
                <label for="flag">Flag</label>
                <select class="form-control" name="flag">
                    <option value="1">Active</option>
                    <option value="0">Non Active</option>
                </select>
            </div>
			<div class="form-group">
				<button type="submit" class="btn btn-md btn-primary">Submit</button>
				<button type="reset" class="btn btn-md btn-danger">Cancel</button>
			</div>
		</form>
	</div>

resources/views/pages/jenisPotongan/index.blade.php
@extends('layouts.master')

@section('title')
    <title>Dashboard</title>
@endsection
@section('content')
<div class="col-md-12" style="background:#fff;">
	@if(Session::has('alert-success'))
	<div class="alert alert-success">
		<strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
	</div>
	@endif
    <div class="row">
        <div class="col-md-8">
            @include('pages.jenisPotongan.data')
        </div>
        <div class="col-md-4">
            @include('pages.jenisPotongan.form')
        </div>
    </div>
</div>
@endsection