routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('data-bank', 'dataBankController');
Route::resource('jenis-cuti', 'jenisCutiController');
Route::get('tambah-data-cuti', function () {
    return view('pages.jenisCuti.form');
});
Route::resource('jenis-golongan', 'jenisGolonganController');
Route::resource('jabatan', 'dataJabatanController');
Route::resource('jenis-potongan', 'jenisPotonganController');
Route::resource('komponen-gaji', 'komponenGajiController');
Route::resource('karyawan-tetap', 'karyawanTetapController');
Route::resource('karyawan-kontrak', 'karyawanKontrakController');
Route::resource('kontrak-karyawan', 'dataKontrakController');

app/Http/Controllers/jenisGolonganController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\jenisGolongan;

class jenisGolonganController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = jenisGolongan::all();
        return view('pages.jenisGolongan.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.jenisGolongan.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'namaGolongan' => 'required|min:4',
            'nominal' => 'required|min:4',
            'flag' => 'required',
        ]);

        $data = new jenisGolongan();
       $data->nama_golongan = $request->namaGolongan;
       $data->nominal = $request->nominal;
       $data->flag = $request->flag;
       $data->save();
       return redirect()->route('jenis-golongan.index')->with('alert-success','Berhasil Menambahkan Jenis Golongan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $ids = $request->idgolongan;
        $datas = jenisGolongan::where('id',$ids)->first();
        $datas->nama_golongan = $request->namaGolongan;
        $datas->nominal = $request->nominal;
        $datas->flag = $request->flag;
        $datas->save();
        return redirect()->route('jenis-golongan.index')->with('alert-success','Berhasil diUpdate Jenis Golongan!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $datas = jenisGolongan::where('id',$id)->first();
        $datas->delete();
        return redirect()->route('jenis-golongan.index')->with('alert-success','Berhasil diHapus Jenis Golongan!');
    }
}

resources/views/pages/jenisGolongan/data.blade.php
<div class="container-fluid">
		<h2>Table Data Golongan</h2>
		<hr>
		<table class="table table-bordered">
			<thead class="table-primary">
				<tr>
					<th>Nama Golongan</th>
					<th>Nominal</th>
					<th>Flag</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				@foreach($data as $datas)
				<tr>
					<th>{{ $datas->nama_golongan }}</th>
					<th>{{ $datas->nominal }}</th>
					<th>{{ $datas->flag }}</th>
					<td>
						<form action="{{ route('jenis-golongan.destroy', $datas->id) }}" method="POST">
							{{ csrf_field() }}
							{{ method_field('DELETE') }}
							<a href="#" data-toggle="modal" data-target="#exampleModal" data-namagolongan="{{$datas->nama_golongan}}" data-nominal="{{$datas->nominal}}" data-idgolongan="{{$datas->id}}" class="btn btn-sm btn-primary">Edit</a>
							<button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
						</form>
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Data</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('jenis-golongan.update',1) }}" method="POST" >
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <input type="hidden" readonly="readonly" class="form-control idgolongan" name="idgolongan" required="required">
                    <div class="form-group">
                        <label for="namaGolongan">Nama Golongan</label>
                        <input type="text" class="form-control namagolongan" name="namaGolongan" required="required">
                    </div>
                    <div class="form-group">
                        <label for="nominal">Nominal</label>
                        <input type="number" class="form-control nominal" name="nominal" required="required">
                    </div>
                    <div class="form-group">
                        <label for="flag">Flag</label>
                        <select class="form-control" name="flag">
                            <option value="1">Active</option>
                            <option value="0">Non Active</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-md btn-primary">Submit</button>
                        <button type="reset" class="btn btn-md btn-danger">Cancel</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>

<script>
    $('#exampleModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget)
        var jenisgolongan = button.data('namagolongan')
        var nominal = button.data('nominal')
        var id = button.data('idgolongan')
        var modal = $(this)

        modal.find('.modal-body .namagolongan').val(jenisgolongan)
        modal.find('.modal-body .nominal').val(nominal)
        modal.find('.modal-body .idgolongan').val(id)
    })
</script>

resources/views/pages/jenisGolongan/form.blade.php
<div class="container-fluid">
		<h2>Input Data Golongan</h2>
		<hr>
		@if ($errors->any())
	    <div class="alert alert-danger">
	        <ul>
	        @foreach ($errors->all() as $error)
	            <li>{{ $error }}</li>
	        @endforeach
	        </ul>
	    </div>
	    @endif
		<form action="{{ route('jenis-golongan.store') }}" method="POST" >
			{{ csrf_field() }}
			<div class="form-group">
				<label for="namaGolongan">Nama Golongan</label>
				<input type="text" class="form-control" name="namaGolongan" required="required">
			</div>
			<div class="form-group">
				<label for="nominal">Nominal</label>
				<input type="number" class="form-control" name="nominal" required="required">
			</div>
			<div class="form-group">
                <label for="flag">Flag</label>
                <select class="form-control" name="flag">
                    <option value="1">Active</option>
                    <option value="0">Non Active</option>
                </select>
            </div>
			<div class="form-group">
				<button type="submit" class="btn btn-md btn-primary">Submit</button>
				<button type="reset" class="btn btn-md btn-danger">Cancel</button>
			</div>
		</form>
	</div>

resources/views/pages/jenisGolongan/index.blade.php
@extends('layouts.master')

@section('title')
    <title>Dashboard</title>
@endsection
@section('content')
<div class="col-md-12" style="background:#fff;">
	@if(Session::has('alert-success'))
	<div class="alert alert-success">
		<strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
	</div>
	@endif
    <div class="row">
        <div class="col-md-8">
            @include('pages.jenisGolongan.data')
        </div>
        <div class="col-md-4">
            @include('pages.jenisGolongan.form')
        </div>
    </div>
</div>
@endsection