routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('data-bank', 'dataBankController');
Route::resource('jenis-cuti', 'jenisCutiController');
Route::get('tambah-data-cuti', function () {
    return view('pages.jenisCuti.form');
});
Route::resource('jenis-golongan', 'jenisGolonganController');
Route::resource('jabatan', 'dataJabatanController');
Route::resource('jenis-potongan', 'jenisPotonganController');
Route::resource('komponen-gaji', 'komponenGajiController');
Route::resource('karyawan-tetap', 'karyawanTetapController');
Route::resource('karyawan-kontrak', 'karyawanKontrakController');
Route::resource('kontrak-karyawan', 'dataKontrakController');

app/Http/Controllers/komponenGajiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\komponenGaji;

class komponenGajiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = komponenGaji::all();
        return view('pages.komponenGaji.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.komponenGaji.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'idKomponen' => 'required|min:4',
            'idBatchGaji' => 'required|min:4',
            'nominal' => 'required|min:4',
            'flag' => 'required',
        ]);

        $data = new komponenGaji();
        // $data->id_komponen = $request->idKomponen;
        // $data->id_batch_gaji = $request->idBatchGaji;
        // $data->nominal = $request->nominal;
        // $data->flag = $request->flag;
        $data->komponen=$request->komponen;
        $data->tipe_komponen=$request->tipe_komponen;
        $data->flag=1;
        $data->created_at=date('Y-m-d H:i:s');
        $data->updated_at=date('Y-m-d H:i:s');
        $data->save();
       return redirect()->route('komponen-gaji.index')->with('alert-success','Berhasil Menambahkan Komponen Gaji!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $ids = $request->idd;
        $datas = komponenGaji::where('id',$ids)->first();
        // $datas->id_komponen = $request->idKomponen;
        // $datas->id_batch_gaji = $request->idBatchGaji;
        // $datas->nominal = $request->nominal;
        // $datas->flag = $request->flag;
        $datas->komponen=$request->komponen;
        $datas->tipe_komponen=$request->tipe_komponen;
        $datas->flag=1;
        $datas->updated_at=date('Y-m-d H:i:s');
        $datas->save();
        return redirect()->route('komponen-gaji.index')->with('alert-success','Berhasil diUpdate Komponen Gaji!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $datas = komponenGaji::where('id',$id)->first();
        $datas->flag = 0;
        $datas->save();
        return redirect()->route('komponen-gaji.index')->with('alert-success','Berhasil diHapus Komponen Gaji!');
    }
}

resources/views/pages/komponenGaji/data.blade.php
<div class="container-fluid">
		<h2>Table Data Komponen Gaji</h2>
		<hr>
		<table class="table table-bordered">
			<thead class="table-primary">
				<tr>
					<th>Komponen</th>
					<th>Kategori</th>
					<th>Flag</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				@foreach($data as $datas)
				<tr>
					<th>{{ $datas->komponen }}</th>
					<th>{!! $datas->tipe_komponen==1 ? '<span class="label label-success">Pemasukan</span>':'<span class="label label-warning">potongan</span>' !!}</th>
					<th>{{ $datas->flag }}</th>
					<td>
						<form action="{{ route('komponen-gaji.destroy', $datas->id) }}" method="POST">
							{{ csrf_field() }}
							{{ method_field('DELETE') }}
							<a href="#" data-toggle="modal" data-target="#exampleModal" data-idkomponen="{{$datas->komponen}}" data-idd="{{$datas->id}}" class="btn btn-sm btn-primary">Edit</a>
							<button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
						</form>
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Data</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('komponen-gaji.update', 1) }}" method="POST" >
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <input type="hidden" readonly="readonly" class="form-control idd" name="idd" required="required">
                    <div class="form-group">
                        <label for="idKomponen">Komponen</label>
                        <input type="text" class="form-control idkomponen" name="komponen" required="required">
                    </div>
                    <div class="form-group">
                        <label for="flag">Kategori</label>
                        <select class="form-control" name="tipe_komponen">
                            <option value="1">Pemasukan</option>
                            <option value="0">Potongan</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="flag">Flag</label>
                        <select class="form-control" name="flag">
                            <option value="1">Active</option>
                            <option value="0">Non Active</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-md btn-primary">Submit</button>
                        <button type="reset" class="btn btn-md btn-danger">Cancel</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>

<script>
    $('#exampleModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget)
        var idKomponen = button.data('idkomponen')
        var idBatch = button.data('idbatch')
        var nominal = button.data('nominal')
        var id = button.data('idd')
        var modal = $(this)

        modal.find('.modal-body .idkomponen').val(idKomponen)
        modal.find('.modal-body .idbatch').val(idBatch)
        modal.find('.modal-body .nominal').val(nominal)
        modal.find('.modal-body .idd').val(id)
    })
</script>

resources/views/pages/komponenGaji/form.blade.php
<div class="container-fluid">
		<h2>Input Data Komponen Gaji</h2>
		<hr>
		@if ($errors->any())
	    <div class="alert alert-danger">
	        <ul>
	        @foreach ($errors->all() as $error)
	            <li>{{ $error }}</li>
	        @endforeach
	        </ul>
	    </div>
	    @endif
		<form action="{{ route('komponen-gaji.store') }}" method="POST" >
			{{ csrf_field() }}
			<div class="form-group">
				<label for="idKomponen"> Komponen</label>
				<input type="text" class="form-control" name="komponen" required="required">
			</div>
			<div class="form-group">
                <label for="flag">Kategori</label>
                <select class="form-control" name="tipe_komponen">
                    <option value="1">Pemasukan</option>
                    <option value="0">Potongan</option>
                </select>
            </div>
			<div class="form-group">
                <label for="flag">Flag</label>
                <select class="form-control" name="flag">
                    <option value="1">Active</option>
                    <option value="0">Non Active</option>
                </select>
            </div>
			<div class="form-group">
				<button type="submit" class="btn btn-md btn-primary">Submit</button>
				<button type="reset" class="btn btn-md btn-danger">Cancel</button>
			</div>
		</form>
	</div>

resources/views/pages/komponenGaji/index.blade.php
@extends('layouts.master')

@section('title')
    <title>Dashboard</title>
@endsection
@section('content')
<div class="col-md-12" style="background:#fff;">
	@if(Session::has('alert-success'))
	<div class="alert alert-success">
		<strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
	</div>
	@endif
    <div class="row">
        <div class="col-md-8">
            @include('pages.komponenGaji.data')
        </div>
        <div class="col-md-4">
            @include('pages.komponenGaji.form')
        </div>
    </div>
</div>
@endsection